name: Publish package
on:
  push:
    branches:
      - main

jobs:
  build:
    name: publish
    runs-on: ubuntu-latest
    env:
      MODE: 'production'
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
            bun-version: 1.2.4
            token: ${{ secrets.GITHUB_TOKEN }} 
      - name: Check Environment Mode
        run: echo "Environment Mode is $MODE"
      - run: bun install
      - name: Publish
        run: npm publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
